<?php echo $this->action('top', 'modulo', 'default'); ?>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'tablero', 'action' => 'index'), '', true); ?>">Tablero</a> <span class="divider">/</span></li>
    <li>Modulos <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'modulo', 'action' => 'index','id'=>$this->id_modulo), '', true); ?>">Modulo: <strong><?php echo $this->dato->nombre_modulo;?></strong></a></li>
</ul>
<h2>Modulo: <?php echo $this->dato->nombre_modulo;?><br /><small>Agregar nuevo item a nuestro modulo</small></h2><br />
<div class="well">
    <h3>RELACIONES - PASO II</h3>
    <?php echo $this->formulario_relacion;?>
</div>