<?php echo $this->action('top', 'modulo', 'default'); ?>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'tablero', 'action' => 'index'), '', true); ?>">Tablero</a> <span class="divider">/</span></li>
    <li class="active">Ayuda</li>
</ul>
<h2>¡ Ayuda ! <small>&iquest;Tienes problemas?. Contactanos y resolveremos tus dudas</small></h2><br />