<div class="page-header">
    <h1>Sin permiso de acceso</h1>
    <h2><small>Debes tener ingresar tu <strong>email</strong> y <strong>clave</strong> para ingresar al sistema.</small></h2>
    <h2><small>Si ya realizaste este paso anteriormente signifca que no tienes permiso de acceder a este modulo del CMS.</small></h2>
</div>
<a class="btn btn-primary btn-large" href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index'),'',true);?>">¡ Quiero acceder !</a>