<?php echo $this->action('top', 'usuario', 'default'); ?>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'tablero', 'action' => 'index'), '', true); ?>">Tablero</a> <span class="divider">/</span></li>
    <li class="active">Usuarios</li>
</ul>
<div class="span4">
    <div class="well">
        <h4>Crear usuario</h4>
        <?php echo $this->formulario; ?>
    </div>
</div>
<div class="span7">
    <?php if ($this->error) : ?>
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡ERROR!</h2> No fue posible ejecutar esta acción, intenta nuevamente.
        </div>   
    <?php elseif ($this->exito) : ?>   
        <div class="alert alert-success">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡EXITO!</h2> Se ejecuto exitosamente esta acción.
        </div>        
    <?php endif; ?>     
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Email</th>
                <th>Clave</th>
                <th>Tipo</th>
                <th class="span1">Acciones</th>            
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->datos as $retorno) : ?>            
                <tr>
                    <td><?php echo $retorno->nombre_usuario; ?></td>
                    <td><?php echo $retorno->email_usuario; ?></td>
                    <td><?php echo $retorno->clave_usuario; ?></td>
                    <td><?php echo $retorno->nombre_tipo; ?></td>
                    <td>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-primary btn-mini dropdown-toggle">Acción <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <!--<li><a href="#"><i class="icon-pencil"></i> Editar</a></li>-->
                                <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'usuario', 'action' => 'eliminar', 'id' => $retorno->id_usuario), '', true); ?>"><i class="icon-trash"></i> Borrar</a></li>
                                <?php if($retorno->tipo_usuario <> 1) :?>
                                <li><a data-toggle="modal" href="#myModal<?php echo $retorno->id_usuario; ?>"><i class="icon-list-alt"></i> Modulos</a></li>
                                <?php endif;?>
                            </ul>
                        </div>              
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>    
</div>
<?php foreach ($this->datos as $retorno) : ?>     
    <div class="modal" id="myModal<?php echo $retorno->id_usuario; ?>" style="display: none">
        <div class="modal-header">
            <a href="#" class="close" data-dismiss="modal">×</a>
            <h3>Modulos</h3>
            <h4><small>Los modulos que sean marcados al usuario, podra acceder al momento de ingresar al CMS</small></h4>
        </div>
        <div class="modal-body">
            <?php $datos = $this->modulo->obtener($retorno->id_usuario);?>
            <?php $this->formulariomodulo->populate(array('id_usuario' => $retorno->id_usuario,'id_modulo'=>$datos)); ?>
            <?php echo $this->formulariomodulo; ?>
        </div>
    </div>  
<?php endforeach; ?>