<div class="page-header">
    <h1><?php echo $this->titulo;?><br /><small><?php echo $this->resumen;?></small></h1>
</div>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero'),'',true);?>/">Inicio</a> <span class="divider">/</span></li>
    <li class="active">Mi perfil</li>
</ul>
<br /><br /> 
<?php if ($this->error) : ?>
    <div class="alert alert-error">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <h2>¡ERROR!</h2> No fue posible ejecutar esta acción, intenta nuevamente.
    </div>   
<?php elseif ($this->exito) : ?>   
    <div class="alert alert-success">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <h2>¡EXITO!</h2> Se ejecuto exitosamente esta acción.
    </div>        
<?php endif; ?>
<div class="well">
    <h3>ACTUALIZA TUS DATOS</h3>
    <?php echo $this->formulario;?>
</div>